name: flutter_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  google_sign_in: ^6.1.5
  http: ^1.2.0
  flutter_secure_storage: ^9.0.0
  flutter_local_notifications: ^17.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  syncfusion_flutter_maps: ^28.1.38
  signalr_netcore: ^1.4.3
  location: ^5.0.3
  flutter_dotenv: ^5.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  xml: ^6.3.0
  flutter_map_animations: ^0.6.0


flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.production
    - assets/images/